# Generated by Django 2.0.7 on 2018-08-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Area name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=100)),
                ('motto', models.TextField(help_text='Motto')),
                ('email', models.EmailField(help_text='E-mail', max_length=254)),
                ('exp', models.TextField(blank=True, help_text='Experience')),
                ('edu', models.TextField(blank=True, help_text='Education')),
                ('photo', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='areas',
            name='persons',
            field=models.ManyToManyField(blank=True, help_text='People in this area', to='main.Person'),
        ),
    ]
