# Generated by Django 2.0.7 on 2018-08-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180808_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='post',
            field=models.CharField(default='HR', help_text='Post', max_length=300),
        ),
    ]
