# Generated by Django 2.0.7 on 2018-08-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_person_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='areas',
            name='photo',
            field=models.ImageField(blank=True, help_text='Practice photo', upload_to=''),
        ),
    ]
