# Generated by Django 2.0.7 on 2018-08-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Area name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=100)),
                ('motto', models.TextField(help_text='Motto')),
                ('email', models.EmailField(help_text='E-mail', max_length=254)),
                ('exp', models.TextField(help_text='Experience')),
                ('edu', models.TextField(help_text='Education')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='_type',
            field=models.CharField(help_text='Post type', max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.EmailField(help_text='More info link', max_length=254),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(help_text='Publication date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='quote',
            field=models.TextField(help_text='Post quote'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(help_text='Post text'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(help_text='Title'),
        ),
        migrations.AddField(
            model_name='areas',
            name='persons',
            field=models.ManyToManyField(help_text='People in this area', to='news.Person'),
        ),
    ]
