# Generated by Django 2.0.7 on 2018-08-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180807_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Type name', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='_type',
        ),
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.EmailField(blank=True, help_text='More info link', max_length=254),
        ),
        migrations.AlterField(
            model_name='article',
            name='quote',
            field=models.TextField(blank=True, help_text='Post quote'),
        ),
        migrations.AlterField(
            model_name='person',
            name='edu',
            field=models.TextField(blank=True, help_text='Education'),
        ),
        migrations.AlterField(
            model_name='person',
            name='exp',
            field=models.TextField(blank=True, help_text='Experience'),
        ),
        migrations.AddField(
            model_name='newstype',
            name='articles',
            field=models.ManyToManyField(help_text='Articles of this type', to='news.Article'),
        ),
    ]
