# Generated by Django 2.0.7 on 2018-08-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180807_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='areas',
            name='persons',
            field=models.ManyToManyField(blank=True, help_text='People in this area', to='news.Person'),
        ),
        migrations.AlterField(
            model_name='newstype',
            name='articles',
            field=models.ManyToManyField(blank=True, help_text='Articles of this type', to='news.Article'),
        ),
    ]
