# Generated by Django 2.0.7 on 2018-08-08 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180808_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areas',
            name='persons',
        ),
        migrations.DeleteModel(
            name='Areas',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
